// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqsgjkubzncdjysunplm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxc2dqa3Viem5jZGp5c3VucGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDQwMjAsImV4cCI6MjA2MTkyMDAyMH0.QD8X7-qE0NwKGZ_TBDNYCrQrxZPfPKO6qz0yTXbbgy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);